### ISSUE TITLE
Ability to exclude plugins from loader

### ISSUE THREAD

**Issue by cfoellmann** [bueltge/must-use-loader#10]
Usecase:
I run (try to run) Mercator (https://github.com/humanmade/Mercator) for domain mapping. It is included in sunrise.php and the folder(s) sit in `mu-plugins`.
Now I don't want it to be loaded by the must-use-loader.

I wasn't sure if filters work so early but I tested and the code I added works. Not sure if there are any situations this can lead to issues.

Filter usage:
```php
function prefix_unset_autoloading( $mu_plugins ) {

	unset($mu_plugins["mercator-gui/gui.php"]);
	unset($mu_plugins["mercator-sso/sso.php"]);

	return $mu_plugins;
}
add_filter( 'mustuse_loader_mu_plugins', 'prefix_unset_autoloading' );
```

**Comment by bueltge** [comment]
Merged. Thanks a lot!
