### ISSUE TITLE
Composer package

### ISSUE THREAD

**Issue by DannyvanHolten** [bueltge/must-use-loader#4]
Will you make this a composer package in packagist?

**Comment by DannyvanHolten** [comment]
Sorry, seen it already is. Maybe nice to include a small composer require part in the readme so people can see it.

**Comment by bueltge** [comment]
Yes, it is also a packager on packagist.org - https://packagist.org/packages/bueltge/must-use-loader
Maybe you send also a request for the hint inside the readme?

**Comment by bueltge** [comment]
What do you @DannyvanHolten think, is this enough to find a little bid help?

**Comment by DannyvanHolten** [comment]
Yeah :) Very good. Thanx :). If we could now release it as a new version I would be able te remove the VCS and directly load it from your source :)

**Comment by bueltge** [comment]
Now, the new release is public, also on packagist.
Thanks for your help and hints.
